const gulp = require("gulp");
// const less = require("less");
const sass = require('gulp-sass')(require('sass'));
const del = require("del");
const cleanCss = require("gulp-clean-css");
const rename = require("gulp-rename");
const babel = require("gulp-babel");
const uglify =  require("gulp-uglify");
const concat = require("gulp-concat");
const sourcemaps = require("gulp-sourcemaps");
const autoPrefixer = require("gulp-autoprefixer");
const imagein = require("gulp-imagemin");
const htmlmin = require('gulp-htmlmin');
const gulpSize = require("gulp-size");
const newer = require("gulp-newer");
var browserSync = require('browser-sync').create();

const paths = {
	html : {
		src : "index.html",
		dest : "dist/"
	},
	styles : {
		src : `src/styles/**/*.sass`,
		dest : "dist/css/"
	},
	scripts : {
		src : `src/scripts/**/*.js`,
		dest : "dist/js/"
	},
	images : {
		src : "src/img/*",
		dest: "dist/images"
	},
}

function clean(){
	return del(["dist/*" ,"!dist/images"])
}

function styles(){
	return gulp.src(paths.styles.src)
	.pipe(sourcemaps.init())
	.pipe(sass())
	.pipe(autoPrefixer({
		cascade : false
	}))
	.pipe(cleanCss(
		{level : 2}
	))
	.pipe(rename({
		basename: "main",
		suffix : ".min"
	}))
	.pipe(sourcemaps.write())
	.pipe(gulpSize(
		{showFiles:  true}
	))
	.pipe(gulp.dest(paths.styles.dest))
	.pipe(browserSync.stream())
}

function  scripts(){
	return  gulp.src(paths.scripts.src)
	.pipe(sourcemaps.init())
	.pipe(babel({
		presets: ['@babel/env']
	}))
	.pipe(uglify())
	.pipe(concat("main.min.js"))
	.pipe(sourcemaps.write("."))
	.pipe(gulpSize(
		{showFiles:  true}
	))
	.pipe(gulp.dest(paths.scripts.dest))
	.pipe(browserSync.stream())
}

function watch(){
	browserSync.init({
        server: "dist/"
    })
	gulp.watch(paths.html.src , minifyHtml)
	gulp.watch(paths.html.dest).on("change" ,browserSync.reload)
	gulp.watch(paths.styles.src, styles)
	gulp.watch(paths.scripts.src, scripts)
}

function img(){
	return gulp.src(paths.images.src)
	.pipe(newer(paths.images.dest))
	.pipe(imagein())
	.pipe(gulp.dest(paths.images.dest))
}


function minifyHtml(){
	return gulp.src(paths.html.src)
	.pipe(htmlmin({	includeAutoGeneratedTags: true,
		removeAttributeQuotes: true,
		removeComments: true,
		removeRedundantAttributes: true,
		removeScriptTypeAttributes: true,
		removeStyleLinkTypeAttributes: true,
		sortClassName: true,
		useShortDoctype: true,
		collapseWhitespace: true}))
	.pipe(gulpSize(
		{showFiles:  true}
	))
	.pipe(gulp.dest(paths.html.dest))
	.pipe(browserSync.stream())
}

const build =  gulp.series(clean,gulp.parallel(minifyHtml,styles,scripts,img),watch)


exports.clean = clean;
exports.styles = styles;
exports.watch = watch;
exports.build = build;
exports.default = build;
exports.scripts = scripts
exports.img = img;
exports.minifyHtml = minifyHtml